CHARACTERS = [
    "Heavy Weapons Clone Trooper",
    "Clone Trooper",
    "Commander Bly",
    "Echo",
    "Fives",
    "Jek",
    "Lieutenant Thire",
    "Captain Rex",
    "Boil",
    "Commander Cody",
    "Hevy",
    "Rys",
    "Waxer",
    "Commander Fil",
    "Commander Ponds",
    "Workout Clone Trooper",
    "Commander Stone",
    "Clone Pilot",
    "Chewbacca (Classic)",
    "Obi-Wan Kenobi",
    "Anakin Skywalker",
    "Padme Amidala",
    "Ahsoka",
    "Pirate Ruffian",
    "Admiral Yularen",
    "Plo Koon",
    "Asajj Ventress",
    "Kit Fisto",
    "Nahdar Vebb",
    "Jar Jar Binks",
    "Dr. Nuvo Vindi",
    "Count Dooku",
    "Aayla Secura",
    "Nute Gunray",
    "Mace Windu",
    "Chancellor Palpatine",
    "Cad Bane",
    "Gamorrean Guard",
    "Bail Organa",
    "Wat Tambor",
    "Aurra Sing",
    "Shahan Alama",
    "Onaconda Farr",
    "Turk Falso",
    "Han Solo (Classic)",
    "Queen Neeyutnee",
    "Barriss Offee",
    "Senate Commando",
    "Senate Commando (Captain)",
    "Poggle the Lesser",
    "Geonosian Guard",
    "Undead Geonosian",
    "Lok Durd",
    "Hondo Ohnaka",
    "Darth Sidious (Classic)",
    "Luminara Unduli",
    "Eeth Koth",
    "Senator Philo",
    "Adi Gallia",
    "Neimoidian",
    "Captain Typho",
    "Jango Fett",
    "Tusken Raider (Classic)",
    "Bib Fortuna",
    "Luxury Droid",
    "Senator Kharrus",
    "Sionver Boll",
    "Ki-Adi-Mundi",
    "Rebel Commando (Classic)",
    "Luke Skywalker (Classic)",
    "Princess Leia (Classic)",
    "Lando Calrissian (Classic)",
    "Imperial Guard (Classic)",
    "Greedo (Classic)",
    "Grand Moff Tarkin",
    "Vader's Apprentice (Classic)",
    "Darth Vader Battle Damaged (Classic)",
    "Darth Vader (Classic)",
    "Darth Maul (Classic)",
    "Captain Antilles (Classic)",
    "Boba Fett (Classic)",
    "Admiral Ackbar (Classic)",
    "Wedge Antilles (Classic)",
    "Clone Shadow Trooper (Classic)",
    "Stormtrooper (Classic)",
    "Obi-Wan Kenobi (Classic)",
    "Qui-Gon Jinn (Classic)",
    "Whorm Loathsom",
    "Battle Droid",
    "Battle Droid Commander",
    "General Grievous",
    "R2-D2",
    "R3-S6",
    "Super Battle Droid",
    "Heavy Super Battle Droid",
    "Gold Super Battle Droid",
    "Droideka",
    "MagnaGuard",
    "C-3PO",
    "Commando Droid",
    "IG-86",
    "Gonk Droid",
    "TX-20",
    "Probe Droid",
    "R6-H5",
    "HELIOS-3D",
    "LEP Servant Droid",
    "MSE-6",
    "R4-P17",
    "Yoda",
    "Wag Too",
    "Lurmen Villager",
    "Robonio",
    "Tee Watt Kaa",
]